robot_hardware:
  - hw_upper_body
  - hw_lower_body
  - hw_i2c

dynamixel_inits:
  init_common:
    - init_return_delay
    - init_operating_mode
    - init_temp_limit
    - init_volt_limit
    - init_vel_limit
    - init_min_pos
    - init_max_pos

  init_indirect:
    - init_indirect_torque
    - init_indirect_hwerr
    - init_indirect_volt_l
    - init_indirect_volt_h
    - init_indirect_temp

  init_pid_low:
    - init_pid_low_p
    - init_pid_low_i
    - init_pid_low_d
    - init_pid_low_ff2
    - init_pid_low_ff1

  init_pid_med:
    - init_pid_med_p
    - init_pid_med_i
    - init_pid_med_d
    - init_pid_med_ff2
    - init_pid_med_ff1

  init_pid_high:
    - init_pid_high_p
    - init_pid_high_i
    - init_pid_high_d
    - init_pid_high_ff2
    - init_pid_high_ff1

  init_return_delay: [9, 1, 0]
  init_operating_mode: [11, 1, 3]
  init_temp_limit: [31, 1, 75]
  init_volt_limit: [32, 2, 135]
  init_vel_limit: [44, 4, 1023]
  init_min_pos: [52, 4, 0]
  init_max_pos: [48, 4, 4095]

  init_indirect_torque: [168, 2, 64]
  init_indirect_hwerr: [170, 2, 70]
  init_indirect_volt_l: [172, 2, 144]
  init_indirect_volt_h: [174, 2, 145]
  init_indirect_temp: [176, 2, 146]

  init_pid_low_p: [84, 2, 640]
  init_pid_low_i: [82, 2, 0]
  init_pid_low_d: [80, 2, 4000]
  init_pid_low_ff2: [88, 2, 0]
  init_pid_low_ff1: [90, 2, 0]

  init_pid_med_p: [84, 2, 2560]
  init_pid_med_i: [82, 2, 0]
  init_pid_med_d: [80, 2, 4000]
  init_pid_med_ff2: [88, 2, 0]
  init_pid_med_ff1: [90, 2, 0]

  init_pid_high_p: [84, 2, 4000]
  init_pid_high_i: [82, 2, 0]
  init_pid_high_d: [80, 2, 4000]
  init_pid_high_ff2: [88, 2, 0]
  init_pid_high_ff1: [90, 2, 0]


hw_upper_body:
  type: mh5_hardware/MH5DynamixelBus
  joints:
    - head_p
    - head_y
    - l_sho_p
    - l_sho_r
    - l_elb_y
    - l_elb_p
    - r_sho_p
    - r_sho_r
    - r_elb_y
    - r_elb_p
  port: /dev/ttySC0
  baudrate: 2000000
  protocol: 2.0
  rs485: true
  loop_rates:
    pvl_reader: 100.0
    stat_reader: 2.0
    pv_writer: 100.0
    t_writer: 2.0
  head_p:
    id: 51
    inverse: true
    inits: [init_common, init_indirect, init_pid_low]
  head_y:
    id: 52
    inits: [init_common, init_indirect, init_pid_low]
  l_sho_p:
    id: 34
    inverse: true
    inits: [init_common, init_indirect, init_pid_low]
  l_sho_r:
    id: 33
    inverse: true
    inits: [init_common, init_indirect, init_pid_low]
  l_elb_y:
    id: 32
    inverse: true
    inits: [init_common, init_indirect, init_pid_low]
  l_elb_p:
    id: 31
    inits: [init_common, init_indirect, init_pid_low]
  r_sho_p:
    id: 44
    inits: [init_common, init_indirect, init_pid_low]
  r_sho_r:
    id: 43
    inits: [init_common, init_indirect, init_pid_low]
  r_elb_y:
    id: 42
    inits: [init_common, init_indirect, init_pid_low]
  r_elb_p:
    id: 41
    inverse: true
    inits: [init_common, init_indirect, init_pid_low]

hw_lower_body:
  type: mh5_hardware/MH5DynamixelBus
  port: /dev/ttySC1
  baudrate: 2000000
  protocol: 2.0
  rs485: true
  loop_rates:
    pvl_reader: 100.0
    stat_reader: 2.0
    pv_writer: 100.0
    t_writer: 2.0
  joints:
    - l_hip_r
    - l_hip_p
    - l_kne_p
    - l_kne_y
    - l_ank_p
    - l_ank_r
    - r_hip_r
    - r_hip_p
    - r_kne_p
    - r_kne_y
    - r_ank_p
    - r_ank_r
  # sensors:
  #   - l_foot
  #   - r_foot
  l_hip_r:
    id: 16
    inverse: true
    # profile: 1
    inits: [init_common, init_indirect, init_pid_high]
  l_hip_p:
    id: 15
    inverse: true
    # profile: 1
    inits: [init_common, init_indirect, init_pid_high]
  l_kne_p:
    id: 14
    inverse: true
    # profile: 1
    offset: 1.570796326794897
    inits: [init_common, init_indirect, init_pid_high]
  l_kne_y:
    id: 13
    inverse: true
    # profile: 1
    inits: [init_common, init_indirect, init_pid_high]
  l_ank_p:
    id: 12
    inverse: true
    # profile: 1
    inits: [init_common, init_indirect, init_pid_high]
  l_ank_r:
    id: 11
    # profile: 1
    inits: [init_common, init_indirect, init_pid_high]
  r_hip_r:
    id: 26
    # profile: 1
    inits: [init_common, init_indirect, init_pid_high]
  r_hip_p:
    id: 25
    inverse: true
    # profile: 1
    inits: [init_common, init_indirect, init_pid_high]
  r_kne_p:
    id: 24
    inverse: true
    # profile: 1
    offset: 1.570796326794897
    inits: [init_common, init_indirect, init_pid_high]
  r_kne_y:
    id: 23
    # profile: 1
    inits: [init_common, init_indirect, init_pid_high]
  r_ank_p:
    id: 22
    inverse: true
    # profile: 1
    inits: [init_common, init_indirect, init_pid_high]
  r_ank_r:
    id: 21
    inverse: true
    # profile: 1
    inits: [init_common, init_indirect, init_pid_high]
  l_foot:
    id: 19
  r_foot:
    id: 29

hw_i2c:
  type: mh5_hardware/MH5I2CInterface
  port: /dev/i2c-1
  rates:
    imu: 200.0
    adc: 1.0
  imu:
    id: 106
    lpf: 0.1
    # orientation: [ 0.7071068, 0.0, -0.7071068, 0.0 ]
